Vagrant.configure(2) do |config|
 config.vm.box = "ubuntu/trusty64"
 config.vm.network "forwarded_port", guest: 3306, host: 3306
 config.vm.provision "shell", path: "docker_install.sh"
 config.vm.provider "virtualbox" do |v|
  v.name = "faw"
  v.memory = 2048
  v.cpus = 2
 end
end